# Generated by Django 4.1.2 on 2022-10-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_district_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('AGE', models.CharField(max_length=2)),
                ('Gender', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('adress', models.TextField(max_length=100)),
                ('materials', models.BooleanField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.branch')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
    ]
