# Generated by Django 4.1.2 on 2022-10-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_form_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_register',
            name='Cheque_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form_register',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form_register',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
    ]
