# Generated by Django 4.1.2 on 2022-10-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_form_register_cheque_book_form_register_credit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_register',
            name='materials',
        ),
    ]
